#!/bin/bash

get_ip()
{
  if type "ifconfig" > /dev/null 2>&1 ; then
    webip=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
  else
    webip="0.0.0.0"
  fi
}

get_ip
cd /src
jekyll serve --host $webip --port 4000
