#!/bin/bash -eux

cd $(readlink -m "$0/..")
SPEC=pitrery.spec

#       B U I L D

sudo yum-builddep -y ${SPEC}
rpmbuild \
    --define "_rpmdir ${PWD}" \
    --undefine _disable_source_fetch \
    -ba ${SPEC}

VERSION=$(rpmspec --query --queryformat '%{VERSION}-%{RELEASE}' ${SPEC})
ln -nfvs "noarch/pitrery-${VERSION}.noarch.rpm" pitrery-last.rpm
chown -R "$(stat -c %u:%g $SPEC)" noarch/ pitrery-last.rpm

#       T E S T

sudo yum install -y pitrery-last.rpm
/usr/bin/pitrery -V
