#!/bin/bash -eux

cd $(readlink -m $0/..)
SPEC=pitrery.spec

#       B U I L D

sudo yum-builddep -y ${SPEC}
rpmbuild \
    --define "_rpmdir ${PWD}" \
    --undefine _disable_source_fetch \
    -ba ${SPEC}

#       T E S T

VERSION=$(rpmspec --query --queryformat '%{VERSION}-%{RELEASE}' ${SPEC})
ln -nfvs "noarch/pitrery-${VERSION}.noarch.rpm" pitrery-last.rpm
sudo yum install -y pitrery-last.rpm
/usr/bin/pitrery -V
