#! /bin/sh

set -e

case "$1" in
	upgrade)
		if [ -e /usr/bin/archive_xlog ] ; then
			rm -f /usr/bin/archive_xlog
			ln -s /usr/bin/archive_wal /usr/bin/archive_xlog
		fi
		if [ -e /usr/bin/restore_xlog ] ; then
			rm -f /usr/bin/restore_xlog
			ln -s /usr/bin/restore_wal /usr/bin/restore_xlog
		fi
	;;
esac
