#! /bin/sh

set -e

case "$1" in
  upgrade)
    if [ -e /usr/bin/archive_xlog ] && [ ! -h /usr/bin/archive_xlog ] ; then
      touch /usr/bin/archive_xlog_to_wal
    fi
    if [ -e /usr/bin/restore_xlog ] && [ ! -h /usr/bin/restore_xlog ] ; then
      touch /usr/bin/restore_xlog_to_wal
    fi
  ;;
esac
