#! /bin/sh

set -e

case "$1" in
    remove)
        if [ -h /usr/bin/archive_xlog ] ; then
            rm -f /usr/bin/archive_xlog
        fi
        if [ -h /usr/bin/restore_xlog ] ; then
           rm -f /usr/bin/restore_xlog
        fi
    ;;
esac
