#!/bin/bash -eux

#
# Script to run tests
#

top_srcdir=$(readlink -m $0/../..)
cd ${top_srcdir}

export PGDATA=/tmp/pgsql
export PITRERY_BACKUP_DIR=/tmp/backup
export PITRERY_LOCAL_CONF=/tmp/pitrery_local.conf
export PATH=/usr/local/bin:$PATH:.

teardown() {
	exit_code=$?

	# If not on CI and we are docker entrypoint (PID 1), let's wait forever on
	# error. This allows user to enter the container and debug after a build
	# failure.
	if [ -z "${CI-}" -a $PPID = 1 -a $exit_code -gt 0 ] ; then
		tail -f /dev/null
	fi

	# stop and destroy PG cluster
	${PGBIN}/pg_ctl stop -w -D ${PGDATA}
	rm -rf ${PGDATA}
	rm -rf $PITRERY_BACKUP_DIR

	# stop and destroy PG cluster number 2
	${PGBIN}/pg_ctl stop -w -D ${PGDATA}_2
	rm -rf ${PGDATA}_2
	rm -rf ${PITRERY_BACKUP_DIR}_2

	exit ${exit_code}
}

trap teardown EXIT INT TERM

for candidate in /usr/pgsql-${PGVERSION}/bin /usr/lib/postgresql/${PGVERSION}/bin ; do
    if PGBIN=$(readlink -e $candidate) ; then
        break
    fi
done
test -n "$PGBIN"
export PGBIN

# init PG cluster
${PGBIN}/initdb -D ${PGDATA}

# Setup archiving
echo "archive_mode = on" >> ${PGDATA}/postgresql.auto.conf
WAL_LEVEL='replica'
[[ ${PGVERSION} == '9.5' ]] && WAL_LEVEL='hot_standby'
echo "wal_level = '${WAL_LEVEL}'" >> ${PGDATA}/postgresql.auto.conf
echo "archive_command = '$(type -p archive_wal) -a /tmp/backup/archived_wal %p'" >>${PGDATA}/postgresql.auto.conf

# start PG
${PGBIN}/pg_ctl start -w -D ${PGDATA} -l /tmp/logfile

# create backup directory
mkdir -p $PITRERY_BACKUP_DIR

# initiate WAL archiving
xlog_or_wal="wal"
first_digit_version=$( echo $PGVERSION | cut -d'.' -f1 )
if [[ (( $first_digit_version -lt 10 )) ]]; then
	xlog_or_wal="xlog"
fi
export xlog_or_wal
${PGBIN}/psql -c "SELECT pg_switch_${xlog_or_wal}()"

# run bats tests
bats -t t/func.bats
